### ISSUE TITLE
关于Release里的固件

### ISSUE THREAD

**Issue by pexcn** [rssnsj/openwrt-xiaomi-mini#1]
这不是小米路由器mini的固件吗？为什么写着“极1s和极2“通用呢？难道写错了？

**Comment by rssnsj** [comment]
是的，写错了。已修正，多谢！

**Comment by pexcn** [comment]
对了，那个刷机方式不是用mtd刷的吧。。当时编译完直接mtd -r write xxx.bin xxx 结果起不来。后来刷回官方了。。是不是先刷pandorabox，然后再用sysupgrade刷？
