### ISSUE TITLE
mtd command does not work

### ISSUE THREAD

**Issue by davidshen84** [rssnsj/openwrt-xiaomi-mini#17]
The original command:

> mtd -r write openwrt-ramips-mt7620a-xiaomi-miwifi-mini-squashfs-sysupgrade.bin firmware

no longer works. Some people say **firmware** should be changed to **OS1** due to changes in the latest developer ROM.

The ROM I got from xiaomi.com is _miwifi_r1cm_firmware_4156a_2.5.22_

**Comment by rssnsj** [comment]
Thanks for letting me know!
