### ISSUE TITLE
这是小米路由器Mini的固件吗？

### ISSUE THREAD

**Issue by pexcn** [rssnsj/openwrt-xiaomi-mini#2]
我编译后用mtd的方式刷进去，但是开不了机。之后又试了sysupgrade的方式刷入，还是不能开机。之后又直接下载了release的固件，还是不行。难道这不是小米路由器mini的openwrt？

**Comment by pexcn** [comment]
原来是默认不开启2.4Ghz

**Comment by wang0z** [comment]
求教一下。按照你的描述，貌似你提前更新了uboot是吧？

**Comment by pexcn** [comment]
@wang0z 不是，默认不开启2.4GHz而已，开了就行

**Comment by rssnsj** [comment]
刷机方法请参见项目首页的README

**Comment by wang0z** [comment]
谢谢
