### ISSUE TITLE
貌似没有5G

### ISSUE THREAD

**Issue by valkjsaaa** [rssnsj/openwrt-xiaomi-mini#4]
如题...

**Comment by skefer** [comment]
我编译出来也没有5G，不知道是什么原因

**Comment by valkjsaaa** [comment]
现在貌似有了？

**Comment by rssnsj** [comment]
你自己编译的是没有5G驱动的，本项目不包含5G驱动源码，因为MTK有版权限制。

**Comment by catinred2** [comment]
[这里](https://wiki.openwrt.org/toh/xiaomi/mini)提到

> To enable the 5ghz wifi, install kmod-mt76 with opkg or via the webinterface.

@rssnsj 试过成功吗？
