### ISSUE TITLE
刷了启动不了

### ISSUE THREAD

**Issue by jjm2473** [rssnsj/openwrt-xiaomi-mini#6]
编译至少生成了以下文件
1. openwrt-ramips-mt7620a-root.squashfs
2. openwrt-ramips-mt7620a-uImage.bin
3. openwrt-ramips-mt7620a-xiaomi-miwifi-mini-squashfs-sysupgrade.bin

我把1刷进"rootfs",2刷进"kernel"后启动不了.

**Comment by jjm2473** [comment]
可以生成类似PandoraBox那样的单一镜像吗

**Comment by rssnsj** [comment]
刷机命令：

```
mtd write openwrt-ramips-mt7620a-xiaomi-miwifi-mini-squashfs-sysupgrade.bin firmware
```

**Comment by rssnsj** [comment]
更新了一下readme，可以参考。

**Comment by jjm2473** [comment]
谢谢.不过比较新的官方固件已经没有"firmware"这个区了.

**Comment by rssnsj** [comment]
你可以研究一下，不是OS1就是OS2。

**Comment by jjm2473** [comment]
等机器回来再看看。不过我刷过PandoraBox，分区的名称都变了，不知道要怎么刷。
